name: Build Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: nint8835/workflows/.github/workflows/docker-build.yaml@main
    with:
      image_name: nint8835/discord-whitelist
